export const MAGIC_CIRCLE_RENDERING_CONFIG = {
    VIEWBOX_SIZE: 260,
    CENTER: 130,
    INNER_RADIUS: 34,
    OUTER_RADIUS: 93,
    OUTER_FRAME_RADIUS: 122,
    SINGLE_NODE_RADIUS: 60,
    INNER_GUIDE_RADIUS: 30,
    OUTER_GUIDE_RADIUS: 116,
    CORE_GRADIENT_RADIUS: 126,
    CORE_GLOW_RADIUS: 5,
    CORE_DOT_RADIUS: 1.6,
    NODE_STAR_MIN_POINTS: 3,
    NODE_RING_ECHO_OFFSET: 3.5,
    OUTER_BAND_PADDING: 14,
    OUTER_GLYPH_CLEARANCE: 2,
    GLYPH_DESIGN_RADIUS: 9,
    MIN_OUTER_BAND_SPACING: 18,
    MIN_GLYPH_SCALE: 0.68,
    MAX_GLYPH_SCALE: 1.02,
    GLYPH_SCALE_RADIUS: 104,
    GLYPH_INDEX_COUNT_STEP: 2,
    GLYPH_INDEX_COUNT_STEP_LIMIT: 3,
    HALF_TURN_DEGREES: 180,
    FULL_TURN_DEGREES: 360,
    SVG_UP_DEGREES: 90,
    BASE_SPIN_SECONDS: 18,
    SPIN_STEP_SECONDS: 5,
    DENSE_RING_THRESHOLD: 4,
    RING_STROKE_WIDTH: 1.4,
    DENSE_RING_STROKE_WIDTH: 1.15,
    LIGHTWEIGHT_NODE_THRESHOLD: 100,
    LIGHTWEIGHT_GLYPH_MARK_LIMIT: 8,
    LOOP_BREATHE_SECONDS: 9,
    BURST_SPIN_SECONDS: 0.8,
    BURST_BREATHE_SECONDS: 0.8,
} as const;

export const MAGIC_CIRCLE_ANIMATION_MODES = {
    STATIC: 'static',
    BURST: 'burst',
    LOOP: 'loop',
} as const;

export type MagicCircleAnimationMode =
    (typeof MAGIC_CIRCLE_ANIMATION_MODES)[keyof typeof MAGIC_CIRCLE_ANIMATION_MODES];

export const NODE_COMPOSITION_TRANSITION_CONFIG = {
    FILL_DURATION_MS: 520,
    SPIN_DURATION_MS: MAGIC_CIRCLE_RENDERING_CONFIG.BURST_SPIN_SECONDS * 1000,
    FLASH_DURATION_MS: 420,
    REDUCED_MOTION_DURATION_MS: 180,
    MAX_CIRCLE_INSTANCES: 12,
    CIRCLE_STAGGER_MS: 36,
    ORBIT_DURATION_MS: 1600,
    CENTRAL_CIRCLE_SIZE: 'clamp(220px, 34vmin, 420px)',
    ORBITING_CIRCLE_SIZE: 'clamp(104px, 15vmin, 190px)',
    ORBIT_RADIUS: 'clamp(142px, 31vmin, 360px)',
} as const;
